name: nutrivision
description: "NutriVision - AI-powered food nutrition tracker"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any

  # State Management
  flutter_riverpod: any
  riverpod_annotation: any

  # Navigation
  go_router: any

  # Camera & Image
  camera: any
  image_picker: any

  # AI / Gemini
  google_generative_ai: any

  # UI
  cupertino_icons: ^1.0.8
  fl_chart: any
  shimmer: any
  cached_network_image: any
  lottie: any
  google_fonts: any
  flutter_animate: any
  icons_plus: any

  # Utils
  intl: any
  uuid: any
  equatable: any
  dartz: any
  internet_connection_checker: any
  shared_preferences: any
  permission_handler: any
  image: any
  path_provider: any
  flutter_hooks: any
  hooks_riverpod: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  riverpod_generator: any
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
